version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    environment:
      NAME: "Ndo Samy Stephan"
    steps:
      - checkout
      - run:
          name: "Print hello world on the file"
          command: "echo Hello! $NAME - ${CIRCLE_USERNAME} > output.txt"
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Print File"
          command: "cat output.txt"
    
workflows:
  print_hello_workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - print_hello
