version: 2.1

commands:
  print_pipeline_id:
    parameters:
      id:
        type: string
        default: "None"
    steps: 
      - run: echo <<parameters.id>>

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  print_id:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id:
        id: $CIRCLE_WORKFLOW_ID
    
workflows:
  reuse_code:
    jobs:
      - print_id
